In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

In [2]:
data = pd.read_csv('new_churn_data.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26996 entries, 0 to 26995
Data columns (total 28 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   user                     26996 non-null  int64
 1   churn                    26996 non-null  int64
 2   age                      26996 non-null  float64
 3   housing                  26996 non-null  object
 4   deposits                 26996 non-null  int64
 5   withdrawal               26996 non-null  int64
 6   purchases_partners       26996 non-null  int64
 7   purchases                26996 non-null  int64
 8   cc_taken                 26996 non-null  int64
 9   cc_recommended           26996 non-null  int64
 10  cc_disliked              26996 non-null  int64
 11  cc_liked                 26996 non-null  int64
 12  cc_application_begin     26996 non-null  int64
 13  app_downloaded           26996 non-null  int64
 14  web_user                 26996 non-null  int64
 15  ios_user                 26996 non-null  int64
 16  android_user             26996 non-null  int64
 17  registered_phones        26996 non-null  int64
 18  payment_type             26996 non-null  object
 19  waiting_4_loan           26996 non-null  int64
 20  cancelled_loan           26996 non-null  int64
 21  received_loan            26996 non-null  int64
 22  rejected_loan            26996 non-null  int64
 23  zodiac_sign              26996 non-null  object
 24  left_for_two_month_plus  26996 non-null  int64
 25  left_for_one_month       26996 non-null  int64
 26  reward_rate              26996 non-null  float64
 27  is_referred              26996 non-null  int64
dtypes: float64(2), int64(23), object(3)
memory usage: 5.8+ MB

In [6]:
data.head(30)

,user,churn,age,housing,deposits,withdrawal,purchases_partners,purchases,cc_taken,cc_recommended,...,payment_type,waiting_4_loan,cancelled_loan,received_loan,rejected_loan,zodiac_sign,left_for_two_month_plus,left_for_one_month,reward_rate,is_referred
0,55409,0,37.0,na,0,0,0,0,0,0,...,Bi-Weekly,0,0,0,0,Leo,1,0,0.00,0
1,23547,0,28.0,R,0,0,1,0,0,96,...,Weekly,0,0,0,0,Leo,0,0,1.47,1
2,58313,0,35.0,R,47,2,86,47,0,285,...,Semi-Monthly,0,0,0,0,Capricorn,1,0,2.17,0
3,8095,0,26.0,R,26,3,38,25,0,74,...,Bi-Weekly,0,0,0,0,Capricorn,0,0,1.10,1
4,61353,1,27.0,na,0,0,2,0,0,0,...,Bi-Weekly,0,0,0,0,Aries,1,0,0.03,0
5,3120,1,32.0,R,5,3,111,5,0,227,...,Bi-Weekly,0,0,0,0,Taurus,0,0,1.83,0
6,41406,0,21.0,na,0,0,4,0,0,0,...,Bi-Weekly,0,0,0,0,Cancer,0,0,0.07,0
7,67679,0,24.0,na,0,0,2,0,0,0,...,na,0,0,0,0,Leo,0,0,0.11,0
8,21269,0,28.0,R,0,0,0,0,2,47,...,Bi-Weekly,0,0,0,0,Sagittarius,0,0,0.87,1
9,25788,0,23.0,na,1,0,87,1,0,125,...,Bi-Weekly,0,0,0,0,Aquarius,0,0,1.07,0
10,13840,0,32.0,R,0,0,30,0,0,70,...,Monthly,0,0,0,0,Virgo,0,0,0.83,1
11,25899,0,41.0,O,14,0,116,13,0,217,...,Semi-Monthly,0,0,0,0,Virgo,0,0,2.17,0
12,20839,0,20.0,na,0,0,135,0,0,286,...,Bi-Weekly,0,0,0,0,Libra,0,0,2.20,1
13,13019,0,27.0,O,2,1,48,2,0,127,...,Weekly,0,0,0,0,Gemini,0,0,1.00,0
14,24387,0,47.0,na,11,1,20,11,0,30,...,Bi-Weekly,0,0,0,0,Virgo,0,0,0.69,1
15,65427,1,44.0,na,0,0,0,0,1,4,...,Semi-Monthly,0,0,0,0,Libra,0,0,0.07,0
16,30419,1,24.0,na,6,2,24,6,0,55,...,Weekly,0,0,0,0,Capricorn,0,0,0.90,0
17,30693,0,31.0,R,17,2,62,17,0,180,...,na,0,0,0,0,Libra,0,0,1.43,0
18,69531,0,20.0,na,0,0,0,0,0,0,...,Monthly,0,0,0,0,Sagittarius,1,0,0.00,0
19,34733,1,30.0,na,2,1,0,2,0,9,...,Bi-Weekly,0,0,0,0,Libra,1,0,0.07,0
20,66712,1,59.0,na,0,0,0,0,0,0,...,Bi-Weekly,0,0,0,0,Gemini,0,0,0.00,0
21,15359,1,21.0,na,0,0,0,0,0,3,...,Bi-Weekly,0,0,0,0,Sagittarius,0,0,0.00,0
22,25997,0,37.0,R,0,0,39,0,0,74,...,na,0,1,0,0,Scorpio,0,0,1.33,0
23,13813,1,30.0,R,6,0,11,6,0,20,...,Bi-Weekly,0,0,0,0,Gemini,0,0,0.40,0
24,67807,0,36.0,na,0,0,2,0,0,0,...,Bi-Weekly,0,0,0,0,Aquarius,0,0,0.50,0
25,19184,1,44.0,O,0,0,0,0,3,4,...,Monthly,0,0,0,0,Scorpio,0,1,0.17,0
26,34210,1,52.0,na,0,0,0,0,0,74,...,Bi-Weekly,0,0,0,0,Pisces,1,0,1.30,0
27,57598,1,25.0,na,0,0,0,0,0,32,...,Monthly,0,0,0,0,Virgo,0,0,0.47,0
28,57608,1,22.0,na,0,0,0,0,1,67,...,Bi-Weekly,0,0,0,0,Pisces,0,0,0.90,0
29,8381,0,38.0,na,0,0,27,0,0,30,...,Bi-Weekly,0,0,0,0,Libra,0,0,1.00,0

In [7]:
data.isnull()

,user,churn,age,housing,deposits,withdrawal,purchases_partners,purchases,cc_taken,cc_recommended,...,payment_type,waiting_4_loan,cancelled_loan,received_loan,rejected_loan,zodiac_sign,left_for_two_month_plus,left_for_one_month,reward_rate,is_referred
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26991,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26992,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26993,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26994,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [9]:
x=data.iloc[:,6:8].values
y=data.iloc[:,8].values

In [10]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=12)

In [11]:
logregres = LogisticRegression()

In [12]:
logregres.fit(x_train,y_train)

C:\Users\ASUS\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [14]:
predictions = logregres.predict(x_test)

In [15]:
predictions

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [16]:
confusion_matrix(y_test,predictions)

array([[5168,    0,    0,    0,    0,    0,    0,    0],
       [ 167,    0,    0,    0,    0,    0,    0,    0],
       [  38,    0,    0,    0,    0,    0,    0,    0],
       [  14,    0,    0,    0,    0,    0,    0,    0],
       [   7,    0,    0,    0,    0,    0,    0,    0],
       [   3,    0,    0,    0,    0,    0,    0,    0],
       [   2,    0,    0,    0,    0,    0,    0,    0],
       [   1,    0,    0,    0,    0,    0,    0,    0]], dtype=int64)

In [17]:
logregres.score(x_test, y_test)

0.957037037037037